repos:
  -   repo: https://github.com/pre-commit.sh/pre-commit.sh-hooks
      rev: v2.3.0
      hooks:
        -   id: check-yaml
        -   id: end-of-file-fixer
        -   id: trailing-whitespace
  -   repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
        -   id: black
#repos:
#  - repo: git://github.com/pecigonzalo/pre-commit.sh-shfmt
#    rev: 9ee28e3f14556aa88dd5255f2e091d1d2f607bb7
#    hooks:
#      - id: shell-fmt
#
#  - repo: git://github.com/pre-commit.sh/pre-commit.sh-hooks
#    rev: v1.2.3
#    hooks:
#      - id: check-yaml
#      - id: check-json
#      - id: end-of-file-fixer
#      - id: trailing-whitespace
#      - id: check-case-conflict
#      - id: check-merge-conflict
