/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */

@RunWith(classOf[JUnitRunner])
class AppSuite extends AnyFunSuite {
//  test("App has a greeting") {
//    assert(App.greeting() != null)
//  }
}
